@include('admin.include.header')

            <!-- ========== REPORTS CONTENT START ========== -->
            <div class="content-area">
                <!-- Report Controls -->
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="row g-3">
                            <div class="col-md-3">
                                <label class="form-label">Report Type</label>
                                <select class="form-select">
                                    <option selected>Usage Report</option>
                                    <option>User Report</option>
                                    <option>Revenue Report</option>
                                    <option>System Report</option>
                                </select>
                            </div>
                            <div class="col-md-3">
                                <label class="form-label">Date Range</label>
                                <select class="form-select">
                                    <option selected>This Month</option>
                                    <option>Last Month</option>
                                    <option>Last 3 Months</option>
                                    <option>This Year</option>
                                </select>
                            </div>
                            <div class="col-md-3">
                                <label class="form-label">Format</label>
                                <select class="form-select">
                                    <option selected>View Online</option>
                                    <option>PDF</option>
                                    <option>Excel</option>
                                    <option>CSV</option>
                                </select>
                            </div>
                            <div class="col-md-3">
                                <label class="form-label">&nbsp;</label>
                                <button class="btn btn-primary w-100">
                                    <i class="fas fa-download"></i> Generate Report
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Report Charts -->
                <div class="row mb-4">
                    <div class="col-lg-6 mb-3">
                        <div class="card chart-card">
                            <div class="card-header border-0 pb-0">
                                <h5 class="card-title mb-0">Monthly Revenue Trend</h5>
                                <small class="text-muted">Last 12 months</small>
                            </div>
                            <div class="card-body">
                                <canvas id="revenueChart"></canvas>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6 mb-3">
                        <div class="card chart-card">
                            <div class="card-header border-0 pb-0">
                                <h5 class="card-title mb-0">User Growth</h5>
                                <small class="text-muted">Quarterly comparison</small>
                            </div>
                            <div class="card-body">
                                <canvas id="userGrowthChart"></canvas>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Recent Reports -->
                <div class="card table-card">
                    <div class="card-header border-0">
                        <h5 class="card-title mb-0">Generated Reports</h5>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-hover mb-0">
                            <thead>
                                <tr class="table-header-blue">
                                    <th>Report Name</th>
                                    <th>Type</th>
                                    <th>Period</th>
                                    <th>Generated On</th>
                                    <th>Generated By</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <i class="fas fa-file-pdf text-danger me-2"></i>
                                        Monthly Usage Report - January 2026
                                    </td>
                                    <td><span class="badge bg-info">Usage Report</span></td>
                                    <td>Jan 1 - Jan 17, 2026</td>
                                    <td>Jan 17, 2026</td>
                                    <td>Admin User</td>
                                    <td>
                                        <div class="d-flex justify-content-center align-items-center gap-2">
                                        <button class="btn btn-sm btn-outline-primary me-1" title="Download">
                                            <i class="fas fa-download"></i>
                                        </button>
                                        <button class="btn btn-sm btn-outline-danger" title="Delete">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <i class="fas fa-file-excel text-success me-2"></i>
                                        User Analytics Report - December 2025
                                    </td>
                                    <td><span class="badge bg-primary">User Report</span></td>
                                    <td>Dec 1 - Dec 31, 2025</td>
                                    <td>Dec 31, 2025</td>
                                    <td>Admin User</td>
                                    <td>
                                        <div class="d-flex justify-content-center align-items-center gap-2">
                                        <button class="btn btn-sm btn-outline-primary me-1" title="Download">
                                            <i class="fas fa-download"></i>
                                        </button>
                                        <button class="btn btn-sm btn-outline-danger" title="Delete">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <i class="fas fa-file-csv text-info me-2"></i>
                                        Revenue Report - Q4 2025
                                    </td>
                                    <td><span class="badge bg-warning">Revenue Report</span></td>
                                    <td>Oct 1 - Dec 31, 2025</td>
                                    <td>Jan 1, 2026</td>
                                    <td>Admin User</td>
                                    <td>
                                        <div class="d-flex justify-content-center align-items-center gap-2">
                                        <button class="btn btn-sm btn-outline-primary me-1" title="Download">
                                            <i class="fas fa-download"></i>
                                        </button>
                                        <button class="btn btn-sm btn-outline-danger" title="Delete">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <i class="fas fa-file-pdf text-danger me-2"></i>
                                        System Performance Report - November 2025
                                    </td>
                                    <td><span class="badge bg-secondary">System Report</span></td>
                                    <td>Nov 1 - Nov 30, 2025</td>
                                    <td>Nov 30, 2025</td>
                                    <td>Admin User</td>
                                    <td>
                                        <div class="d-flex justify-content-center align-items-center gap-2">
                                        <button class="btn btn-sm btn-outline-primary me-1" title="Download">
                                            <i class="fas fa-download"></i>
                                        </button>
                                        <button class="btn btn-sm btn-outline-danger" title="Delete">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- ========== REPORTS CONTENT END ========== -->
        </div>
        <!-- ========== MAIN CONTENT END ========== -->
    </div>

  @include('admin.include.footer')
    
    <!-- Additional Chart for Reports Page -->
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Revenue Chart
            const ctxRevenue = document.getElementById('revenueChart').getContext('2d');
            const revenueData = {
                labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                datasets: [{
                    label: 'Revenue ($K)',
                    data: [28, 32, 35, 38, 42, 45, 48, 51, 49, 52, 55, 58],
                    borderColor: '#0066cc',
                    backgroundColor: 'rgba(0, 102, 204, 0.1)',
                    borderWidth: 3,
                    fill: true,
                    tension: 0.4,
                    pointRadius: 5,
                    pointBackgroundColor: '#0066cc',
                    pointBorderColor: '#fff',
                    pointBorderWidth: 2,
                }]
            };

            const revenueOptions = {
                responsive: true,
                maintainAspectRatio: true,
                plugins: {
                    legend: {
                        display: true,
                        position: 'top',
                        labels: {
                            font: { family: "'Poppins', sans-serif", size: 14, weight: '500' },
                            color: '#2c3e50',
                            padding: 15,
                            usePointStyle: true
                        }
                    }
                },
                scales: {
                    y: {
                        beginAtZero: true,
                        max: 70,
                        grid: { color: 'rgba(0, 0, 0, 0.05)', drawBorder: false },
                        ticks: {
                            font: { family: "'Poppins', sans-serif", size: 12 },
                            color: '#7f8c8d',
                            stepSize: 10
                        }
                    },
                    x: {
                        grid: { display: false, drawBorder: false },
                        ticks: {
                            font: { family: "'Poppins', sans-serif", size: 12 },
                            color: '#7f8c8d'
                        }
                    }
                }
            };

            new Chart(ctxRevenue, { type: 'line', data: revenueData, options: revenueOptions });

            // User Growth Chart
            const ctxGrowth = document.getElementById('userGrowthChart').getContext('2d');
            const growthData = {
                labels: ['Q1 2025', 'Q2 2025', 'Q3 2025', 'Q4 2025', 'Q1 2026'],
                datasets: [{
                    label: 'New Users',
                    data: [145, 178, 212, 245, 287],
                    backgroundColor: 'rgba(0, 188, 212, 0.8)',
                    borderColor: '#00bcd4',
                    borderWidth: 2,
                    borderRadius: 8
                }]
            };

            const growthOptions = {
                responsive: true,
                maintainAspectRatio: true,
                plugins: {
                    legend: {
                        display: true,
                        position: 'top',
                        labels: {
                            font: { family: "'Poppins', sans-serif", size: 14, weight: '500' },
                            color: '#2c3e50',
                            padding: 15,
                            usePointStyle: true
                        }
                    }
                },
                scales: {
                    y: {
                        beginAtZero: true,
                        max: 350,
                        grid: { color: 'rgba(0, 0, 0, 0.05)', drawBorder: false },
                        ticks: {
                            font: { family: "'Poppins', sans-serif", size: 12 },
                            color: '#7f8c8d',
                            stepSize: 50
                        }
                    },
                    x: {
                        grid: { display: false, drawBorder: false },
                        ticks: {
                            font: { family: "'Poppins', sans-serif", size: 12 },
                            color: '#7f8c8d'
                        }
                    }
                }
            };

            new Chart(ctxGrowth, { type: 'bar', data: growthData, options: growthOptions });
        });
    </script>
